@startuml
actor Customer
participant "Support System" as System
participant "SupportAgent"
participant "Support Ticket" as Ticket
Customer -> System : Create Ticket
Ticket -> System : Create Ticket
Customer -> System : Submit Ticket
activate System

System -> SupportAgent : Assign Ticket
activate SupportAgent

System -> SupportAgent : Assign Tickets and Notify User to see 
activate SupportAgent
System --> SupportAgent : Assign Ticket Some Details
alt
System --> SupportAgent : Assign Ticket Some Details
deactivate SupportAgent
else
System -> SupportAgent : Assign Ticket Some Details
activate SystemSystem
System -> SupportAgent : Assign Tickets and Notify User to see 
activate SupportAgent
end
System -> Customer : Send Response
deactivate System
@enduml

